use @SETUP_ENVIRONMENT@
also, use fatal() from shell_utils instead of a custom function that
does basically the same thing

diff --git a/bin/rpki-object/create_object/tests/empty_manifest.sh.in b/bin/rpki-object/create_object/tests/empty_manifest.sh.in
--- a/bin/rpki-object/create_object/tests/empty_manifest.sh.in
+++ b/bin/rpki-object/create_object/tests/empty_manifest.sh.in
@@ -1,26 +1,17 @@
 #!/bin/sh -e
 
-cd `dirname "$0"`
+@SETUP_ENVIRONMENT@
 
-. ../../../../etc/envir.setup
-
-OUTDIR="`pwd`/empty_manifest"
+OUTDIR="$TESTS_BUILDDIR/empty_manifest"
 rm -rf "$OUTDIR"
 mkdir "$OUTDIR"
 
 TEST_LOG_NAME=empty_manifest
 TEST_LOG_DIR="$OUTDIR"
-. "$RPKI_ROOT/tests/test.include"
-
-
-fail () {
-	echo "$@"
-	exit 1
-}
 
 
 run "gen_key-root" gen_key "$OUTDIR/root.p15" 2048 \
-	|| fail "gen_key root.p15 failed"
+	|| fatal "gen_key root.p15 failed"
 run "create_object-root" create_object CERT \
 	outputfilename="$OUTDIR/root.cer" \
 	subjkeyfile="$OUTDIR/root.p15" \
@@ -35,10 +26,10 @@ run "create_object-root" create_object CERT \
 	ipv4="0.0.0.0/0" \
 	ipv6="::/0" \
 	as=0-4294967295 \
-	|| fail "create_object root.cer failed"
+	|| fatal "create_object root.cer failed"
 
 run "gen_key-mft-ee" gen_key "$OUTDIR/empty_manifest.mft.ee.p15" 2048 \
-	|| fail "gen_key empty_manifest.mft.ee.p15 failed"
+	|| fatal "gen_key empty_manifest.mft.ee.p15 failed"
 run "create_object-mft-ee" create_object CERT \
 	outputfilename="$OUTDIR/empty_manifest.mft.ee.cer" \
 	parentcertfile="$OUTDIR/root.cer" \
@@ -55,7 +46,7 @@ run "create_object-mft-ee" create_object CERT \
 	ipv4=inherit \
 	ipv6=inherit \
 	as=inherit \
-	|| fail "create_object empty_manifest.mft.ee.cer failed"
+	|| fatal "create_object empty_manifest.mft.ee.cer failed"
 run "create_object-mft" create_object MANIFEST \
 	outputfilename="$OUTDIR/empty_manifest.mft" \
 	EECertLocation="$OUTDIR/empty_manifest.mft.ee.cer" \
@@ -64,4 +55,4 @@ run "create_object-mft" create_object MANIFEST \
 	nextUpdate=20490101010101Z \
 	manNum=1 \
 	fileList="" \
-	|| fail "create_object empty_manifest.mft failed"
+	|| fatal "create_object empty_manifest.mft failed"
