only run 'config_get RPKIPort' once

diff --git a/tests/subsystem/runSubsystemTest.sh.in b/tests/subsystem/runSubsystemTest.sh.in
--- a/tests/subsystem/runSubsystemTest.sh.in
+++ b/tests/subsystem/runSubsystemTest.sh.in
@@ -34,8 +34,9 @@ cd "$TESTS_BUILDDIR"
 ./initDB || check_errs $? "initDB failed!"
 
 # check for existing loader and fail if so
-if port_open `config_get RPKIPort`; then
-    echo "ERROR: port `config_get RPKIPort` is already in use.  Aborting subsystem test."
+port=$(config_get RPKIPort)
+if port_open ${port}; then
+    echo "ERROR: port ${port} is already in use.  Aborting subsystem test."
     exit 3
 fi
 
@@ -57,7 +58,7 @@ trap 'kill_loader' EXIT
 run_bg "rcli-w" rcli -w -p
 LOADER_PID=$!
 timeout=15
-while ! port_open `config_get RPKIPort`; do
+while ! port_open ${port}; do
     [ "${timeout}" -gt 0 ] || fatal "timed out waiting for rcli to start"
     sleep 1
     timeout=$((timeout-1))
